FROM python:3.9

WORKDIR /code
ADD . /code

ENV FLASK_APP = Linebot_server.py
ENV FLASK_RUN_HOST = 0.0.0.0

RUN pip install flask line-bot-sdk 

EXPOSE 5000
COPY . .

CMD ["flask", "run"]
#CMD python Linebot_server.py
